/**
 * Celestia — Constellation Data
 * Zodiac constellations with star patterns and ecliptic positions
 */

const ConstellationData = (() => {

    // 12 Zodiac constellations with ecliptic longitude ranges, star patterns
    const zodiac = [
        {
            name: 'Aries',
            symbol: '♈',
            startLon: 0,
            endLon: 30,
            dates: 'Mar 21 – Apr 19',
            element: 'Fire',
            brightStar: 'Hamal',
            description: 'The Ram. One of the faintest zodiac constellations, but historically the first sign as the vernal equinox once fell here.',
            stars: [
                { name: 'Hamal', ra: 2.12, dec: 23.46, mag: 2.0 },
                { name: 'Sheratan', ra: 1.91, dec: 20.81, mag: 2.6 },
                { name: 'Mesarthim', ra: 1.89, dec: 19.29, mag: 3.9 },
                { name: '41 Ari', ra: 2.83, dec: 27.26, mag: 3.6 },
            ],
            lines: [[0,1],[1,2],[0,3]],
        },
        {
            name: 'Taurus',
            symbol: '♉',
            startLon: 30,
            endLon: 60,
            dates: 'Apr 20 – May 20',
            element: 'Earth',
            brightStar: 'Aldebaran',
            description: 'The Bull. Home to the bright star Aldebaran and the Pleiades star cluster, one of the most prominent winter constellations.',
            stars: [
                { name: 'Aldebaran', ra: 4.60, dec: 16.51, mag: 0.9 },
                { name: 'Elnath', ra: 5.44, dec: 28.61, mag: 1.7 },
                { name: 'Alcyone', ra: 3.79, dec: 24.11, mag: 2.9 },
                { name: 'ζ Tau', ra: 5.63, dec: 21.14, mag: 3.0 },
                { name: 'θ² Tau', ra: 4.48, dec: 15.87, mag: 3.4 },
            ],
            lines: [[0,4],[4,1],[0,3],[2,4]],
        },
        {
            name: 'Gemini',
            symbol: '♊',
            startLon: 60,
            endLon: 90,
            dates: 'May 21 – Jun 20',
            element: 'Air',
            brightStar: 'Pollux',
            description: 'The Twins. Represented by Castor and Pollux, two of the brightest stars in the night sky standing side by side.',
            stars: [
                { name: 'Pollux', ra: 7.76, dec: 28.03, mag: 1.2 },
                { name: 'Castor', ra: 7.58, dec: 31.89, mag: 1.6 },
                { name: 'Alhena', ra: 6.63, dec: 16.40, mag: 1.9 },
                { name: 'Mebsuta', ra: 6.38, dec: 25.13, mag: 3.1 },
                { name: 'Tejat', ra: 6.23, dec: 22.51, mag: 2.9 },
            ],
            lines: [[0,1],[0,2],[1,3],[3,4],[2,4]],
        },
        {
            name: 'Cancer',
            symbol: '♋',
            startLon: 90,
            endLon: 120,
            dates: 'Jun 21 – Jul 22',
            element: 'Water',
            brightStar: 'Tarf',
            description: 'The Crab. A faint constellation best known for the Beehive Cluster (M44), a beautiful open star cluster visible to the naked eye.',
            stars: [
                { name: 'Tarf', ra: 8.28, dec: 9.19, mag: 3.5 },
                { name: 'Asellus Australis', ra: 8.74, dec: 18.15, mag: 3.9 },
                { name: 'Acubens', ra: 8.97, dec: 11.86, mag: 4.3 },
                { name: 'Asellus Borealis', ra: 8.72, dec: 21.47, mag: 4.7 },
            ],
            lines: [[0,1],[1,2],[1,3]],
        },
        {
            name: 'Leo',
            symbol: '♌',
            startLon: 120,
            endLon: 150,
            dates: 'Jul 23 – Aug 22',
            element: 'Fire',
            brightStar: 'Regulus',
            description: 'The Lion. A striking constellation with the bright star Regulus and a distinctive sickle-shaped asterism forming the lion\'s mane.',
            stars: [
                { name: 'Regulus', ra: 10.14, dec: 11.97, mag: 1.4 },
                { name: 'Denebola', ra: 11.82, dec: 14.57, mag: 2.1 },
                { name: 'Algieba', ra: 10.33, dec: 19.84, mag: 2.6 },
                { name: 'Zosma', ra: 11.24, dec: 20.52, mag: 2.6 },
                { name: 'Ras Elased', ra: 9.76, dec: 23.77, mag: 3.0 },
            ],
            lines: [[0,2],[2,4],[2,3],[3,1],[0,1]],
        },
        {
            name: 'Virgo',
            symbol: '♍',
            startLon: 150,
            endLon: 180,
            dates: 'Aug 23 – Sep 22',
            element: 'Earth',
            brightStar: 'Spica',
            description: 'The Maiden. The largest zodiac constellation, home to the brilliant blue-white star Spica and the Virgo galaxy cluster.',
            stars: [
                { name: 'Spica', ra: 13.42, dec: -11.16, mag: 1.0 },
                { name: 'Porrima', ra: 12.69, dec: -1.45, mag: 2.7 },
                { name: 'Vindemiatrix', ra: 13.04, dec: 10.96, mag: 2.8 },
                { name: 'Auva', ra: 12.93, dec: 3.40, mag: 3.4 },
                { name: 'Zavijava', ra: 11.84, dec: 1.76, mag: 3.6 },
            ],
            lines: [[0,1],[1,3],[3,2],[1,4]],
        },
        {
            name: 'Libra',
            symbol: '♎',
            startLon: 180,
            endLon: 210,
            dates: 'Sep 23 – Oct 22',
            element: 'Air',
            brightStar: 'Zubeneschamali',
            description: 'The Scales. The only zodiac constellation representing an inanimate object. Associated with justice and balance.',
            stars: [
                { name: 'Zubeneschamali', ra: 15.28, dec: -9.38, mag: 2.6 },
                { name: 'Zubenelgenubi', ra: 14.85, dec: -16.04, mag: 2.7 },
                { name: 'Brachium', ra: 15.07, dec: -25.28, mag: 3.3 },
                { name: 'Zubenelhakrabi', ra: 15.60, dec: -14.79, mag: 3.9 },
            ],
            lines: [[0,1],[1,2],[0,3]],
        },
        {
            name: 'Scorpio',
            symbol: '♏',
            startLon: 210,
            endLon: 240,
            dates: 'Oct 23 – Nov 21',
            element: 'Water',
            brightStar: 'Antares',
            description: 'The Scorpion. One of the most recognizable constellations, dominated by the red supergiant Antares, the "heart of the scorpion."',
            stars: [
                { name: 'Antares', ra: 16.49, dec: -26.43, mag: 1.1 },
                { name: 'Shaula', ra: 17.56, dec: -37.10, mag: 1.6 },
                { name: 'Sargas', ra: 17.62, dec: -42.99, mag: 1.9 },
                { name: 'Dschubba', ra: 16.01, dec: -22.62, mag: 2.3 },
                { name: 'Acrab', ra: 16.09, dec: -19.81, mag: 2.6 },
            ],
            lines: [[4,3],[3,0],[0,1],[1,2]],
        },
        {
            name: 'Sagittarius',
            symbol: '♐',
            startLon: 240,
            endLon: 270,
            dates: 'Nov 22 – Dec 21',
            element: 'Fire',
            brightStar: 'Kaus Australis',
            description: 'The Archer. Points toward the center of the Milky Way, making it one of the richest areas for deep-sky objects.',
            stars: [
                { name: 'Kaus Australis', ra: 18.40, dec: -34.38, mag: 1.8 },
                { name: 'Nunki', ra: 18.92, dec: -26.30, mag: 2.0 },
                { name: 'Ascella', ra: 19.04, dec: -29.88, mag: 2.6 },
                { name: 'Kaus Media', ra: 18.35, dec: -29.83, mag: 2.7 },
                { name: 'Kaus Borealis', ra: 18.47, dec: -25.42, mag: 2.8 },
            ],
            lines: [[0,3],[3,4],[4,1],[1,2],[2,0]],
        },
        {
            name: 'Capricorn',
            symbol: '♑',
            startLon: 270,
            endLon: 300,
            dates: 'Dec 22 – Jan 19',
            element: 'Earth',
            brightStar: 'Deneb Algedi',
            description: 'The Sea-Goat. An ancient constellation representing a mythical creature, half goat and half fish.',
            stars: [
                { name: 'Deneb Algedi', ra: 21.74, dec: -16.13, mag: 2.9 },
                { name: 'Dabih', ra: 20.35, dec: -14.78, mag: 3.1 },
                { name: 'Nashira', ra: 21.67, dec: -16.66, mag: 3.7 },
                { name: 'Algedi', ra: 20.29, dec: -12.51, mag: 3.6 },
            ],
            lines: [[3,1],[1,2],[2,0],[0,3]],
        },
        {
            name: 'Aquarius',
            symbol: '♒',
            startLon: 300,
            endLon: 330,
            dates: 'Jan 20 – Feb 18',
            element: 'Air',
            brightStar: 'Sadalsuud',
            description: 'The Water Bearer. Associated with the rainy season in many ancient cultures. Contains the famous Helix Nebula.',
            stars: [
                { name: 'Sadalsuud', ra: 21.53, dec: -5.57, mag: 2.9 },
                { name: 'Sadalmelik', ra: 22.10, dec: -0.32, mag: 3.0 },
                { name: 'Skat', ra: 22.91, dec: -15.82, mag: 3.3 },
                { name: 'Albali', ra: 20.79, dec: -9.50, mag: 3.8 },
            ],
            lines: [[3,0],[0,1],[1,2]],
        },
        {
            name: 'Pisces',
            symbol: '♓',
            startLon: 330,
            endLon: 360,
            dates: 'Feb 19 – Mar 20',
            element: 'Water',
            brightStar: 'Eta Piscium',
            description: 'The Fish. A large but faint constellation. The vernal equinox currently lies within Pisces due to precession.',
            stars: [
                { name: 'Eta Piscium', ra: 1.52, dec: 15.35, mag: 3.6 },
                { name: 'Gamma Piscium', ra: 23.29, dec: 3.28, mag: 3.7 },
                { name: 'Omega Piscium', ra: 23.99, dec: 6.86, mag: 4.0 },
                { name: 'Alrescha', ra: 2.03, dec: 2.76, mag: 3.8 },
            ],
            lines: [[0,3],[3,1],[1,2]],
        },
    ];

    // Notable non-zodiac stars for sky map background
    const brightStars = [
        { name: 'Sirius', ra: 6.75, dec: -16.72, mag: -1.46 },
        { name: 'Canopus', ra: 6.40, dec: -52.70, mag: -0.74 },
        { name: 'Arcturus', ra: 14.26, dec: 19.18, mag: -0.05 },
        { name: 'Vega', ra: 18.62, dec: 38.78, mag: 0.03 },
        { name: 'Capella', ra: 5.28, dec: 46.00, mag: 0.08 },
        { name: 'Rigel', ra: 5.24, dec: -8.20, mag: 0.13 },
        { name: 'Procyon', ra: 7.65, dec: 5.22, mag: 0.34 },
        { name: 'Betelgeuse', ra: 5.92, dec: 7.41, mag: 0.50 },
        { name: 'Altair', ra: 19.85, dec: 8.87, mag: 0.77 },
        { name: 'Fomalhaut', ra: 22.96, dec: -29.62, mag: 1.16 },
        { name: 'Deneb', ra: 20.69, dec: 45.28, mag: 1.25 },
        { name: 'Polaris', ra: 2.53, dec: 89.26, mag: 1.98 },
    ];

    return {
        zodiac,
        brightStars,
    };
})();
